web:
  image: nginx
  links:
    - app
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  environment:
    - HOST
app:
  image: indiehosters/wader
  volumes:
    - /data/domains:/data/domains:ro
    - ./config.json:/usr/src/app/config.json
